# Generated by Django 2.2 on 2019-09-30 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='canPOST',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='continent',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='country',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='county',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='state',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='wrist_band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrist_band_id', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_child', models.CharField(max_length=100)),
                ('last_name_child', models.CharField(max_length=100)),
                ('picture_child', models.ImageField(upload_to='')),
                ('important_information_child', models.CharField(max_length=100)),
                ('first_name_soc', models.CharField(max_length=100)),
                ('last_name_soc', models.CharField(max_length=100)),
                ('relation_to_child', models.CharField(max_length=100)),
                ('phone_number_soc', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('wrist_band_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.wrist_band')),
            ],
        ),
    ]
