# Generated by Django 2.2 on 2019-10-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20191001_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='picture_child',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
